# Generated by Django 3.0.8 on 2020-07-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B positive'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='has_aids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_covid19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_ebola',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_malaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_practitioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
