# Generated by Django 3.0.8 on 2020-07-08 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('user_field', models.CharField(choices=[('age', 'Age'), ('sex', 'Sex'), ('blood_type', 'Blood Type'), ('genotype', 'Genotype'), ('AIDS_status', 'AIDS Status'), ('malaria_status', 'Malaria Status'), ('ebola_status', 'Ebola Status'), ('COVID19_status', 'COVID19 Status')], default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_aids',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_covid19',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_ebola',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_malaria',
        ),
        migrations.AddField(
            model_name='user',
            name='AIDS_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='COVID19_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='ebola_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='malaria_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='userfieldquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
