# Generated by Django 3.0.8 on 2020-07-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200708_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='AIDS_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='n/a', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='COVID19_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='n/a', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('O-', 'O negative'), ('O+', 'O positive'), ('A-', 'A negative'), ('A+', 'A positive'), ('B-', 'B positive'), ('B+', 'B positive'), ('AB-', 'AB negative'), ('AB+', 'AB positive'), ('n/a', 'Not tested')], default='n/a', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='ebola_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='n/a', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('n/a', 'Not tested')], default='n/a', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='malaria_status',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('n/a', 'Not Tested')], default='n/a', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserFieldQuestion',
        ),
    ]
